'use strict';
const root=document.getElementById('app'),modal=document.getElementById('modal');
let view=state.view||{oa:'current',day:27,finance:'travel',hr:'profile',chat:null,query:'',folder:'全部',zoom:false};
const esc=s=>{const raw=String(s??''),safe=raw.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));return raw==='这是谁的猫？'?`${safe}<img class="chat-cat-photo" src="assets/attachments/${encodeURIComponent('胖橘正脸近照.jpg')}" alt="睁大眼睛看镜头的橘猫">`:safe;};
const btn=(label,action,args='',cls='')=>`<button type="${action==='submit'?'submit':'button'}" class="${cls}" data-action="${action}" ${args}>${label}</button>`;
const badge=(label,cls='')=>`<span class="badge ${cls}">${label}</span>`;
const money=n=>(n>0?'+':'−')+Math.abs(n).toFixed(2);
const personSelect=(name,label,options=DATA.people)=>`<label>${label}<select name="${name}" required><option value="">请选择</option>${options.map(p=>`<option>${esc(p)}</option>`).join('')}</select></label>`;

const AVATARS=new Set(DATA.people);
function avatar(name,extra=''){const person=AVATARS.has(name)?name:name==='🐈'?'橘猫':null;return `<span class="avatar ${extra}">${person?`<img src="assets/avatars/${encodeURIComponent(person)}.jpg" alt="${esc(person==='橘猫'?'橘猫员工证件照':person)}">`:esc((name||'?').slice(-1))}</span>`;}
function toast(s){const t=document.getElementById('toast');t.textContent=s;t.classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('visible'),5200);}
function act(action,payload,success){const r=transition(action,payload);if(!r.ok){toast(r.error);return false;}if(success)toast(success);return true;}
function openModal(title,body,footer=''){modal.innerHTML=`<div class="modalhead"><h2 id="modal-title">${esc(title)}</h2>${btn('关闭','close','','small')}</div><div class="modalbody">${body}</div>${footer?`<div class="modalfoot">${footer}</div>`:''}`;if(!modal.open)modal.showModal();}
function navigate(id){if(!appOpen(id)){toast('该系统将在相关身份核验通过后开放。');return;}state.app=id;persist();render();window.scrollTo(0,0);}
function appName(id){return DATA.apps.find(a=>a[0]===id)?.[1]||'处理结果';}
function heading(title,sub,extra=''){const handler=title==='本月薪资预估'?'<p class="heading-contact">本期薪资经办：贺磊　·　奖金及考勤调整</p>':'';return `<div class="heading"><div><h1>${title}</h1><p>${sub}</p>${handler}</div>${extra}</div>`;}
function attachmentButton(id){const a=DATA.attachments[id];return btn(`<span class="fileicon">${a.file.endsWith('.docx')?'DOC':'JPG'}</span><span class="overflowword">${a.file}<small>${state.attachments.includes(id)?'已查看 · 再次打开':'点击预览附件'}</small></span>`,'attachment',`data-id="${id}"`,'attachment');}
function titleScreen(){
 const progressed=state.notes.length||state.businessDone?.length;
 return `<div class="startscreen"><header class="startheader"><div class="brand"><span class="brand-mark">QH</span><div><strong>启衡协同</strong><small>${DATA.company}</small></div></div><span class="start-status"><i></i> 内部网络已连接</span></header><main class="startmain start-login"><section class="startcopy"><div class="startbadge">QIHENG OFFICE SYSTEM　/　OP-026</div><h1><span>谁替我</span><span>请假</span></h1><p class="subtitle">你只是照常来上班。<br>但系统显示，你已经不在这里了。</p><div class="cover-rule"></div><p class="cover-meta">员工数字工作台<br>考勤 · 审批 · 协同</p></section><section class="login-card"><div class="login-label">员工统一身份认证</div><div class="login-user">${avatar(state.catEndingCleared?'🐈':'张佳诚',state.catEndingCleared?'cat login-avatar':'login-avatar')}<div><strong>张佳诚</strong><small>运营部 · OP-026</small></div><span class="login-status">在职</span></div><div class="login-field"><span>登录账号</span><strong>zhangjiacheng</strong></div><div class="login-field"><span>登录方式</span><strong>公司终端免密认证</strong></div><div class="startactions">${btn(progressed?'继续进入工作台':'进入工作台','start','','primary login-submit')}${progressed?btn('重新开始','restart','','login-secondary'):''}${state.endings.length?btn('结局回溯','replay','','login-secondary'):''}</div><div class="startmeta">系统状态保存在当前浏览器</div></section></main><footer class="startfooter"><span>© 启衡协同科技有限公司</span><span>${btn('清除本机数据','clear','','textbutton')}</span></footer></div>`;
}
function shell(content){return `<header class="topbar"><div class="brand"><span class="brand-mark">QH</span><div><strong>启衡协同</strong><small>员工数字工作台</small></div></div><div class="top-search">搜索应用、审批单或同事</div><div class="userbox"><span class="meta">本月28日　09:12</span>${btn(`${avatar(state.ending==='cat'?'🐈':'张佳诚',state.ending==='cat'?'cat':'')}<span class="username">张佳诚</span>`,'profile','','user-profile')}${btn('退出','title','','ghost small')}</div></header><div class="layout"><nav class="sidebar" aria-label="内部应用"><div class="navlabel">工作应用</div>${DATA.apps.map(([id,label,icon])=>btn(`<span class="navicon">${icon}</span><span>${label}</span>${!appOpen(id)?'<span class="lock">待开放</span>':''}`,'nav',`data-id="${id}" ${!appOpen(id)?'aria-disabled="true"':''}`,`navbutton ${state.app===id?'active':''}`)).join('')}<div class="sidebar-bottom"><div class="navlabel">OP-026 · 广州办公室</div>${btn('退出登录','title','','navbutton')}</div></nav><main class="main"><div class="breadcrumb">启衡工作台　/　${appName(state.app)}</div><div class="fade">${content}</div><div class="footerhint">© 启衡协同科技有限公司 · 数据仅限内部使用</div></main></div>`;}
function desktop(){
 const done=(state.businessDone||[]).length;
 const statusBanner=state.leaveDiscovered?`<div class="banner"><div><div class="timer">OA考勤异常 · QH-LV-27</div><h2>您当前正在休病假</h2><p>休假至本月30日　剩余假期2天23小时</p></div>${btn('查看假单','current','','primary')}</div>`:state.workBlocked?`<div class="banner subtle"><div><div class="timer">业务状态同步异常</div><h2>OP-026 周运营数据复核暂无法提交</h2><p>企业微信有一条与员工状态来源相关的新消息。</p></div>${btn('查看消息','chatopen','data-id="opening"','primary')}</div>`:'';
 const messages=state.workBlocked?`<div class="notification">${avatar('罗子豪')}<div class="grow"><strong>罗子豪</strong><p>佳诚，你那份周报是不是卡住了？</p><time>09:08 · 企业微信</time></div>${btn('查看','chatopen','data-id="opening"','small')}</div>${state.leaveDiscovered?`<div class="notification"><span class="system-avatar">审</span><div class="grow"><strong>${state.solved.todayPresence?'身份信息核验':'当前假单异议'}</strong><p>${state.solved.todayPresence?'历史审批已开放。':'如对当前状态有异议，可核对今日在岗记录。'}</p><time>09:10 · OA审批</time></div>${btn('处理','presencePage','','small')}</div>`:''}`:`<div class="notification"><span class="system-avatar">运</span><div class="grow"><strong>运营中心</strong><p>本周数据复核任务已更新，请在14:00前提交。</p><time>08:56 · 工作通知</time></div>${btn('打开任务','businessOpen','data-id="report"','small')}</div>`;
 const attendance=state.leaveDiscovered?badge('休病假','warn'):state.workBlocked?badge('同步异常','warn'):badge('正常出勤','ok');
 return heading('上午好，张佳诚','本月28日 · 星期一',badge('广州办公室 · 在线'))+statusBanner+`<div class="dashboard-grid"><div class="stack"><section class="card"><div class="cardhead"><h2>我的工作</h2><span class="meta">${done}/3 已完成</span></div><div class="business-list">${[['campaign','华南渠道9月活动排期','今天 11:30','待提交'],['report','OP-026 周运营数据复核','今天 14:00','进行中'],['vendor','秋季专题页素材验收','明天 10:00','待处理']].map(([id,t,due,status])=>`<div class="business-row"><span class="task-dot ${state.businessDone?.includes(id)?'done':''}"></span><div class="grow"><strong>${t}</strong><p>${due} · 负责人 张佳诚</p></div>${badge(state.businessDone?.includes(id)?'已完成':status,state.businessDone?.includes(id)?'ok':'')}${btn('打开','businessOpen',`data-id="${id}"`,'small')}</div>`).join('')}</div>${btn('进入运营工作','nav','data-id="business"','textbutton sectiongap')}</section><section class="card"><div class="cardhead"><h2>消息与待办</h2>${btn('打开企业微信','nav','data-id="chat"','textbutton')}</div>${messages}</section></div><aside class="stack"><section class="card identity"><div class="identityhead">${avatar('张佳诚')}<div><strong>张佳诚</strong><small>运营专员 · OP-026</small></div></div><div class="keyval"><span class="muted">部门</span><span>运营部</span></div><div class="keyval"><span class="muted">地点</span><span>广州</span></div><div class="keyval"><span class="muted">考勤</span>${attendance}</div><div class="statusline">数据来自OA审批系统</div></section><section class="card schedule"><div class="cardhead"><h2>今日日程</h2><span class="meta">28日</span></div><div><time>09:00</time><p>运营晨会 · 3A会议室</p></div><div><time>10:30</time><p>华南渠道周会 · 腾讯会议</p></div><div><time>15:00</time><p>专题页上线检查</p></div></section></aside></div>`;
}
function presencePage(){const done=state.solved.todayPresence;return heading('今日在岗核验','本月28日 · 出勤记录复核',badge(done?'已提交':'待提交',done?'ok':'warn'))+`<section class="card"><form data-form="presenceBatch"><div class="record-select">${DATA.presence.map(([id,time,label,desc])=>`<label class="record-check"><input type="checkbox" name="records" value="${id}" ${state.evidence.includes(id)?'checked':''}><span class="datechip">${time}</span><span class="grow"><strong>${label}</strong><small>${desc}</small></span></label>`).join('')}</div><div class="form-action"><span class="meta">请选择需要一并复核的记录</span>${btn(done?'重新提交':'提交所选记录','submit','','primary')}</div></form>${done?'<div class="infobox sectiongap">四项记录来源一致：本人于28日正常到岗，当前休假状态存在冲突。</div>':''}</section>`;}
function oa(){const tabs=`<div class="tabs">${[['current','当前假单'],['presence','今日在岗'],['history','历史审批'],['logs','操作日志']].map(([id,label])=>btn(label,'oaTab',`data-id="${id}"`,view.oa===id?'active':'')).join('')}</div>`;let content='';if(view.oa==='presence')content=presencePage();else if(view.oa==='current')content=anomaly(27);else if(view.oa==='detail')content=btn('← 返回历史审批','oaTab','data-id="history"','back small')+anomaly(view.day);else if(view.oa==='logs'){content=heading('操作日志','人事记录写入审计');if(!state.solved.travel)content+='<div class="card empty">需完成差旅核验后查询关联操作日志。</div>';else content+=`<div class="card"><p>本月18日 · 来源：人事迁移</p>${btn(state.migrationLog?'再次调取操作日志':'调取7条操作日志','migrationLog','','primary')}${state.migrationLog?`<div class="tablewrap sectiongap"><table><thead><tr><th>写入时间</th><th>动作</th><th>终端 / IP</th><th>登录账号</th></tr></thead><tbody>${DATA.migration.map(([time,title])=>`<tr><td>18日 ${time}</td><td>${title}</td><td>HR-03<br>10.0.0.23</td><td>刘一颖</td></tr>`).join('')}</tbody></table></div><form data-form="migrationSource" class="sectiongap">${personSelect('person','这些记录的操作人是：')}<div class="sectiongap">${btn('核验操作来源','submit','','primary')}</div></form>`:''}</div>`;if(state.solved.compensation)content+=`<section class="card sectiongap"><div class="cardhead"><h2>关联模板审计</h2>${badge('发现首条记录','warn')}</div><p>紧急代提模板的员工主体一直指向OP-026。审计记录中保留了它第一次被创建时的会话。</p>${btn(state.earliest?'再次查看首次创建记录':'查看首次创建记录','templateOrigin','','primary')}</section>`;}else{content=heading('历史审批','按异常发生日期归档；未开放记录将在核验后同步。')+`<section class="card listcard">${DATA.anomalies.map(a=>`<div class="row"><div class="datechip"><small>本月</small><b>${a.day}</b></div><div class="grow"><strong>${allowed(a.gate)?a.title:'身份来源待核验'}</strong><p>${allowed(a.gate)?a.duration:'资料暂未开放'}</p></div>${state.reviewed.includes(a.day)?badge('已核验','ok'):''}${btn(allowed(a.gate)?'查看':'待开放','anomaly',`data-day="${a.day}" ${!allowed(a.gate)?'disabled':''}`,'small')}</div>`).join('')}</section>`;}return tabs+content;}
function anomaly(day){const a=DATA.anomalies.find(x=>x.day===day);if(!a||!allowed(a.gate))return '<div class="empty">资料尚未开放。</div>';return heading(a.title,`申请编号 QH-LV-${String(day).padStart(2,'0')} · 本月${day}日`,badge('审批通过'))+`<section class="card"><div class="facts"><div class="keyval"><span class="muted">申请人</span><span>张佳诚</span></div><div class="keyval"><span class="muted">申请时长</span><span>${a.duration}</span></div><div class="keyval"><span class="muted">所属部门</span><span>运营部</span></div><div class="keyval"><span class="muted">审批状态</span><span>已生效</span></div></div><p class="sectiongap">申请事由：${a.reason}</p>${attachmentButton(a.attachment)}<div class="approval"><p><span class="muted">HR · 林雅雯</span><br>${a.hr}</p><p><span class="muted">系统处理</span><br>${a.impact}</p></div>${day===27?`<div class="warningbox">您当前正在休病假<br>剩余假期：2天23小时<br>请放下工作，安心休息。</div><p class="meta">提交方式：管理员代提。该入口不触发员工本人确认，薪资影响将在月底统一结算。</p>${btn('对当前假单提出异议','presencePage','','primary')}`:''}${day===6?`<div class="infobox">宠物姓名：未填写　/　品种：橘　/　性别：公</div>${btn('核验实际申请人','catUnknown','','small')}`:''}${day===10?`<form data-form="marriage" class="sectiongap">${personSelect('person','根据附件及聊天，填写实际申请人')}${btn(state.solved.marriage?'重新核对':'提交核验','submit','','primary sectiongap')}</form>`:''}${day===18?`<p class="sectiongap muted">来源：历史人事数据导入批次 HR-MOVE-0318。</p>`:''}${day===3?`<form data-form="origin" class="sectiongap"><div class="formgrid">${personSelect('beneficiary','3日实际生病的人')}${personSelect('proposer','最早提出“先挂佳诚”的人')}</div>${btn('提交首次借用追溯','submit','','primary')}</form>`:''}</section>`;}
function hr(){const full=state.solved.todayPresence;return `<div class="tabs">${[['profile','员工档案'],['leave','年假余额'],['pet','宠物医疗']].map(([id,title])=>btn(title,'hrTab',`data-id="${id}"`,view.hr===id?'active':'')).join('')}</div>`+(view.hr==='leave'?leavePage():view.hr==='pet'?petPage():heading('员工档案','人员主数据 / QH-OP-026',badge(full?'多系统资料已同步':'基础资料'))+`<div class="workgrid"><section class="card"><div class="identityhead">${avatar('张佳诚')}<div><strong>张佳诚</strong><small>26岁 / 运营专员 / 运营部</small></div></div>${(full?[['婚姻状态','已婚','OA审批'],['子女数量','1','历史人事系统'],['宠物数量','1','宠物医疗登记'],['居住地址','新家','行政资料']]:[['员工编号','QH-OP-026','人事主数据'],['办公地点','广州','门禁系统'],['在职状态','在职','人事主数据']]).map(([label,value,source])=>`<div class="row"><div><strong>${label}</strong><p>来源：${source}</p></div><span>${value}</span></div>`).join('')}<div class="infobox">${full?'部分字段与本人申报资料不一致。':'跨系统字段未完成一致性校验。'}</div></section><section class="card"><h2>${full?'家庭成员':'组织关系'}</h2>${full?`<div class="keyval"><span>配偶</span><strong>1</strong></div><div class="keyval"><span>子女</span><strong>1</strong></div><div class="keyval"><span>宠物</span><strong>1</strong></div><div class="cat-sticker">${avatar('🐈','cat')}<div>医疗资料完整度最高<br><small>姓名：未填写</small></div></div>`:`<div class="keyval"><span>直属主管</span><strong>罗子豪</strong></div><div class="keyval"><span>成本中心</span><strong>OP-GZ</strong></div><div class="keyval"><span>终端编号</span><strong>OP-026</strong></div>`}</section></div>`);}
function petPage(){if(!state.solved.todayPresence)return heading('宠物医疗档案','员工关联资料')+'<div class="card empty">当前没有可确认归属的宠物医疗记录。</div>';return heading('宠物医疗档案','资料完整度：100% · 信息可信度：高',badge('公 / 橘'))+`<section class="card"><div class="inline"><span style="font-size:65px">🐈</span><div><h2>姓名：未填写</h2><p class="muted">登记员工：张佳诚</p></div></div><div class="row"><div class="grow"><strong>6日 · 绝育术后陪护</strong><p>林雅雯：术后注意保暖。</p></div>${attachmentButton('catSurgery')}</div>${state.solved.travel?`<div class="row"><div class="grow"><strong>18日 · 宠物复诊</strong><p>林雅雯：恢复得挺好。</p></div>${attachmentButton('catReview')}</div>`:''}${state.solved.migration?`<div class="row"><div><strong>复诊情况</strong><p>恢复良好。</p></div>${attachmentButton('catWell')}</div>`:''}<div class="warningbox">主人信息缺失。医疗资料完整，不代表能够确认实际申请人。</div>${state.otherHandled?btn('单独强制删除宠物档案','catDelete','','danger small sectiongap'):''}</section>`;}
function leavePage(){if(!state.solved.migration)return heading('年假余额','年度额度与实际休假核对')+'<div class="card empty">历史迁移记录需先核验，余额明细暂不可用。</div>';return heading('年假余额','年度带薪年假 · 本人实际休年假 0 天')+`<div class="grid stats"><div class="card"><span class="muted">年度年假</span><div class="bigstat">5<span>天</span></div></div><div class="card"><span class="muted">系统剩余</span><div class="bigstat">0<span>天</span></div></div></div><section class="card sectiongap"><div class="warningbox">🎉 恭喜您充分利用了本年度带薪休假！<br>系统已使用：5天　/　本人实际休年假：0天</div><div class="tablewrap"><table><thead><tr><th>发生日期</th><th>类型</th><th>年假占用</th><th>剩余</th><th>来源</th></tr></thead><tbody><tr><td>10日</td><td>婚假转年假</td><td>1天</td><td>4天</td><td>${btn('查看假单','anomaly','data-day="10"','small')}</td></tr><tr><td>23日</td><td>家庭事务</td><td>2天</td><td>2天</td><td>${btn(state.chats.includes('borrowChat')?'已查看转发记录':'查看转发记录','chatopen','data-id="borrowChat"','small')}</td></tr><tr><td>27日</td><td>三天病假预占</td><td>2天</td><td>0天</td><td>${btn(state.chats.includes('recentChat')?'已查看转发记录':'查看转发记录','chatopen','data-id="recentChat"','small')}</td></tr></tbody></table></div><form data-form="leaveBalance"><div class="formgrid">${[['d10','10日占用年假'],['d23','23日占用年假'],['d27','27日预占年假'],['actual','本人实际休年假']].map(([name,label])=>`<label>${label}（天）<input name="${name}" type="number" min="0" max="5" step="1" required></label>`).join('')}</div>${btn('提交余额核验','submit','','primary')}</form></section>`;}
function finance(){if(view.finance==='salary')return `<div class="tabs">${[['travel','差旅报销'],['salary','薪资预估']].map(([id,title])=>btn(title,'financeTab',`data-id="${id}"`,view.finance===id?'active':'')).join('')}</div>`+salaryPage();const tabs=`<div class="tabs">${[['travel','差旅报销'],['salary','薪资预估']].map(([id,title])=>btn(title,'financeTab',`data-id="${id}"`,view.finance===id?'active':'')).join('')}</div>`;if(!state.solved.marriage)return tabs+heading('差旅报销','本月报销记录')+'<div class="card empty">当前账户没有可归集的有效差旅单。</div>';return tabs+heading('差旅报销核验','本月14日 · 申请人：张佳诚',badge('4条并行轨迹','warn'))+`<form data-form="travel"><div class="card"><div class="cardhead"><h2>关联项目记录</h2>${badge('项目协同群')}</div><p>本日四笔报销分别引用XS-14、XZ-14、XM-14与OP-026。</p>${btn(state.chats.includes('tripChat')?'再次查看项目安排':'查看项目安排','chatopen','data-id="tripChat"','small')}</div><div class="grid two sectiongap">${DATA.trips.map(t=>`<section class="card"><div class="cardhead"><h2>${t.city}</h2><span class="meta">14日 ${t.time}</span></div><p>项目编号：${t.project}<br>所属部门：${t.dept}<br>同行人：${t.mate}</p>${btn(state.trips.includes(t.city)?'已查看票据':'查看原始票据','trip',`data-city="${t.city}"`,'small')}${personSelect(t.city,'实际出行 / 在岗人员')}</section>`).join('')}</div><div class="card sectiongap">${btn('提交四城归类','submit','','primary')}${state.solved.travel?'<div class="warningbox sectiongap">同一员工在同一时段存在4条并行活动轨迹。<br>系统建议：后续减少跨城安排。</div>':''}</div></form>`;}
function salaryPage(){if(!state.solved.leaveBalance)return heading('本月薪资预估','本月28日 · 未结算')+'<div class="card empty">本期异常调整仍在计算，暂无完整明细。</div>';return heading('本月薪资预估','相对正常应发基准的变动，不含固定工资。',badge('预估 / 尚未发放'))+`<section class="card"><h2>考勤影响</h2><div class="tablewrap"><table><thead><tr><th>扣款项目</th><th>变动（元）</th><th>来源</th></tr></thead><tbody>${DATA.salary.slice(0,2).map(([n,v])=>`<tr><td>${n}</td><td class="negative">${money(v)}</td><td>异常请假触发</td></tr>`).join('')}</tbody></table></div><div class="warningbox">直接金钱损失合计：−665.52元</div>${!state.salaryViewed?btn('展开全部薪资项目','salary','','primary'):''}</section>${state.salaryViewed?`<section class="card sectiongap"><h2>奖金及福利</h2><div class="tablewrap"><table><thead><tr><th>项目名称</th><th>变动（元）</th><th>状态</th></tr></thead><tbody>${DATA.salary.slice(2).map(([n,v])=>`<tr><td>${n}</td><td class="positive">${money(v)}</td><td>待归类</td></tr>`).join('')}</tbody></table></div><p class="meta">以上项目均处于本月工资预结算，尚未发放至银行卡。</p><div class="grid two sectiongap"><section class="subcard"><h3>人工调整审批单</h3><p>QH-PAY-0928 · 四笔业务奖金</p>${btn(state.compDocs.includes('manual')?'已查看 · 再次打开':'查看审批单','compDocument','data-id="manual"','small')}</section><section class="subcard"><h3>系统福利触发规则</h3><p>婚姻、育儿及宠物字段自动匹配</p>${btn(state.compDocs.includes('automatic')?'已查看 · 再次打开':'查看规则','compDocument','data-id="automatic"','small')}</section></div><form data-form="compensation" class="sectiongap"><h2>补发审批记录核对</h2><p class="meta">根据审批单与系统规则，分别确认两类金额。</p><div class="formgrid"><label>人工补发合计（元）<select name="manual" required><option value="">请选择</option><option>6000</option><option>6484.48</option><option>7150</option></select></label><label>系统自动福利另计（元）<select name="automatic" required><option value="">请选择</option><option>665.52</option><option>1150</option><option>6000</option></select></label></div>${btn('确认审批记录','submit','','primary')}</form>${state.solved.compensation?'<div class="infobox">人工补发合计6000元；系统自动福利1150元另计。<br>考勤扣款已被金额覆盖，但年假及个人资料仍保持现状。</div>':''}</section>`:''}`;}
function drive(){const folderFiles=[['人事','wedding'],['人事','birth'],['行政','box'],['行政','plant'],['人事','emotion'],['临时','catSurgery'],['临时','catReview']];if(!state.solved.travel)return heading('内部共享盘','最近文件',badge('仅限内网'))+`<div class="tabs">${['最近','人事','行政','财务','项目','临时'].map((f,i)=>btn(f,'folder',`data-id="${f}"`,i===0?'active':'')).join('')}</div><div class="card empty">没有最近打开的文件<br><small>部分业务目录需要关联记录后才会显示内容。</small></div>`;return heading('内部共享盘','人事迁移 / 本月18日',badge('仅限内网'))+`<div class="tabs">${['全部','人事','行政','财务','项目','临时'].map(f=>btn(f,'folder',`data-id="${f}"`,view.folder===f?'active':'')).join('')}</div><div class="filegrid">${folderFiles.map(([f,id],i)=>({f,id,i})).filter(x=>view.folder==='全部'||x.f===view.folder).map(({f,id,i})=>`<div class="card filecard">${attachmentButton(id)}<span class="meta">${f} / 创建：18日 ${DATA.migration[i][0]}</span><p class="source">HR回复：${DATA.migration[i][3]}</p></div>`).join('')}</div><section class="card sectiongap"><div class="cardhead"><h2>批量导入记录</h2>${badge('HR-MOVE-0318')}</div><p>导入规则会读取已审批附件的材料类型，并同步更新对应员工的婚姻、子女、住址及宠物字段。</p><div class="warningbox">本批次沿用了“紧急代提”模板中的员工主体：OP-026。</div><div class="tablewrap"><table><thead><tr><th>批次</th><th>文件数</th><th>来源终端</th><th>状态</th></tr></thead><tbody><tr><td>HR-MOVE-0318</td><td>7</td><td>待审计</td><td>导入完成</td></tr></tbody></table></div></section><section class="card sectiongap"><h2 class="overflowword">关于张佳诚异常情况内部说明-严禁外传.zip</h2><p class="muted">关联操作来源确认后可解压。</p>${btn('解压查看','archive',state.solved.migration?'':'disabled','small')}</section>`;}
function chat(){
 let all=DATA.chats.filter(c=>allowed(c.gate));
 const q=view.query.trim();
 if(q.includes('何骏'))all=all.filter(c=>c.id==='weddingChat');
 else if(q.includes('刘一颖'))all=all.filter(c=>c.id==='migrationChat');
 else if(q)all=[];
 else all=all.filter(c=>['opening','hrHelp','catDeny','tripChat','borrowChat','recentChat'].includes(c.id));
 all.sort((a,b)=>b.date-a.date||b.time.localeCompare(a.time));
 const c=DATA.chats.find(c=>c.id===view.chat&&allowed(c.gate));
 let conversation=c?(c.forwardedBy
  ?`<div class="message forwarded-message">${avatar(c.forwardedBy)}<div><div class="name">${c.forwardedBy}</div><div class="bubble">${esc(c.forwardIntro)}</div><div class="forward-card"><div class="forward-head"><strong>聊天记录</strong><span>${c.forwardedBy}、${c.forwardedWith}</span><time>本月${c.date}日　${c.time}</time></div>${c.lines.map(([name,text])=>`<div class="forward-row"><strong>${name}</strong><span>${esc(text)}</span></div>`).join('')}<div class="forward-foot">来自企业微信聊天记录</div></div></div></div>`
  :c.lines.map(([name,text])=>`<div class="message ${name==='张佳诚'?'self':''}">${avatar(name)}<div><div class="name">${name}</div><div class="bubble">${esc(text)}</div></div></div>`).join('')):'';
 if(c?.id==='opening')conversation+=`<div class="forward-card sectiongap"><div class="forward-head"><strong>员工状态来源</strong><span>QH-LV-27</span></div><p class="meta">来自员工状态同步服务</p>${btn('查看来源','discoverLeave','','small')}</div>`;
 return `<div class="wechat-title"><div><h1>企业微信</h1><p>启衡协同科技有限公司</p></div>${badge('内网在线','ok')}</div><div class="wechat-shell ${c?'has-chat':''}"><aside class="wechat-rail">${avatar('张佳诚')}<span class="rail-icon active">聊</span><span class="rail-icon">通</span><span class="rail-icon">日</span><span class="rail-spacer"></span><span class="rail-icon">⚙</span></aside><aside class="chatlist"><div class="search"><form data-form="chatSearch"><input aria-label="搜索消息" type="search" name="q" value="${esc(view.query)}" placeholder="搜索群成员姓名">${btn('搜索','submit','','small')}${view.query?btn('清空','clearSearch','','textbutton'):''}</form></div>${all.length?all.map(item=>btn(`${avatar(DATA.people.includes(item.channel)?item.channel:item.channel[0])}<span class="chat-summary"><strong>${item.channel}</strong><small>${state.chats.includes(item.id)?'':'● '}${item.forwardIntro||item.lines.at(-1)[1]}</small></span><time>${item.date===28?item.time:`${item.date}日`}</time>`,'chatopen',`data-id="${item.id}"`,`chatitem ${view.chat===item.id?'selected':''}`)).join(''):`<div class="empty">${q?'未找到与该成员相关的可用会话':'暂无其他最近会话'}</div>`}</aside><section class="chatpanel">${c?`<div class="chatheader">${btn('‹','chatBack','','small mobile-only')}<div><strong>${c.channel}</strong><small>${DATA.people.includes(c.channel)?'启衡协同员工':'群聊 · 内部会话'}</small></div><span>···</span></div><div class="chatbody"><div class="chatdate">本月${c.date}日　${c.time}</div>${conversation}</div><div class="chatfooter">消息已留存于公司服务器</div>`:'<div class="chat-empty"><span>企</span><p>选择一个会话开始查看</p></div>'}</section></div>`;
}
function business(){const tasks={campaign:['华南渠道9月活动排期','整理广州、深圳两地门店档期，确认物料到店时间。','渠道运营'],report:['OP-026 周运营数据复核','核对本周新增线索、转化率与退款异常，完成周报提交。','数据运营'],vendor:['秋季专题页素材验收','检查供应商提交的首屏、商品卡和移动端切图。','内容运营']};return heading('运营工作','我的任务 · 本周第39周',badge(`${(state.businessDone||[]).length}/3 已完成`,'ok'))+`<section class="card"><div class="tablewrap"><table><thead><tr><th>任务</th><th>业务线</th><th>截止时间</th><th>状态</th><th></th></tr></thead><tbody>${Object.entries(tasks).map(([id,[title,desc,line]],i)=>`<tr><td><strong>${title}</strong><small class="block">${desc}</small></td><td>${line}</td><td>${i===2?'明天 10:00':'今天 '+(i?'14:00':'11:30')}</td><td>${badge(state.businessDone?.includes(id)?'已完成':i===1?'进行中':'待处理',state.businessDone?.includes(id)?'ok':'')}</td><td>${btn('查看任务','businessOpen',`data-id="${id}"`,'small')}</td></tr>`).join('')}</tbody></table></div></section>`;}
function selfPage(){if(!state.solved.origin)return heading('本人信息确认','员工资料联合确认')+'<section class="card empty">当前没有待本人签署的确认单。<br><small>已完成的跨系统核验将在此汇总。</small></section>';return heading('本人信息确认','异常资料联合核验 / 待员工确认',badge('7个异常日已核验','ok'))+`<section class="card"><div class="tablewrap"><table><thead><tr><th>信息项目</th><th>${state.otherHandled?'原异常记录（已处理）':'当前记录'}</th><th>来源与部门意见</th></tr></thead><tbody>${[['婚姻信息','已婚','10日 / HR：新婚快乐。'],['子女信息','1','18日 / HR：恭喜。'],['宠物信息','1 · 医疗完整','6日、18日 / HR：注意术后护理。'],['年假记录','已使用5天 / 本人0天','10日、23日、27日 / 系统：使用率100%。'],['差旅记录','一天四城','14日 / 财务：行程紧凑，安排合理。'],['住址信息','新家','18日 / 行政：乔迁顺利。'],['薪资补贴','人工补偿6000 / 系统福利1150','财务：直接金钱损失已覆盖。']].map(([a,b,c])=>`<tr><td>${a}</td><td>${b}</td><td>${c}</td></tr>`).join('')}</tbody></table></div><div class="approval"><p>HR意见：资料已核对。</p><p>财务意见：差额已补。</p><p>行政意见：建议保留现有记录。</p><p>直属主管意见：未参与本次资料核验。</p><p>系统建议：确认并归档。</p></div><div class="warningbox">如删除全部异常并恢复考勤：追回系统误发福利1150元；与异常关联的人工补偿奖金6000元一并冲回；恢复扣款665.52元；恢复5天年假。相较当前预估，收入减少6484.48元。</div><div class="inline">${btn('删除全部异常记录','goodConfirm','','small')}${btn('暂不处理','ending','data-id="normal"','small')}</div><div class="sectiongap">${btn('其他问题 / 其他意见','opinionOpen','','textbutton')}</div>${state.selfOpinionUnlocked?`<div class="infobox">“但是我们没让你亏钱啊。”<br>张佳诚：我知道。<br>张佳诚：可是我的意见呢？</div><form data-form="trueEnding"><label>本人意见<textarea name="opinion" rows="3" placeholder="以后涉及我的事情，请先问我。"></textarea></label><label class="sectiongap"><input name="confirmRequired" type="checkbox" required>身份使用需本人确认</label><p class="meta">保留纠正信息，并记录本次本人意见。</p>${btn('保留纠正信息并启用本人确认','submit','','primary')}</form>`:''}<div class="sectiongap">${btn(state.otherHandled?'其他异常已处理 · 宠物待核验':'逐项处理异常','handleOthers','','textbutton')}${state.otherHandled?`<div class="infobox">其他异常已纠正。宠物资料来源仍无法确认。</div>${btn('🐾','catDelete','aria-label="单独处理宠物档案"','ghost small')}`:''}</div></section>`;}
function endingPage(){const id=state.ending;const names={true:['TRUE END','我的意见呢'],good:['GOOD END','本人'],normal:['NORMAL END','那就这样吧'],cat:['HIDDEN END','喵']};const [code,title]=names[id]||names.normal;let body='';if(id==='true')body=`<div class="endquote">“但是我们没让你亏钱啊。”<br>张佳诚：我知道。<br>张佳诚：可是我的意见呢？</div><div class="infobox">本人意见已保存。<br>后续涉及本人身份信息的操作，必须经本人确认。</div><section class="card sectiongap"><div class="cardhead"><h2>新的身份借用申请</h2>${badge(state.catChoice?'已由本人处理':'待本人确认','warn')}</div><p>用途：宠物复诊</p>${attachmentButton('catReview')}<div class="inline sectiongap">${btn('同意','catChoice','data-id="同意"','primary')}${btn('拒绝','catChoice','data-id="拒绝"')}</div>${state.catChoice?`<p class="source">本人处理结果：${esc(state.catChoice)}。这次，系统等到了你的意见。</p>`:''}</section>`;if(id==='good')body=`<div class="endquote">张佳诚<br>运营专员<br>正常出勤</div><div class="infobox">全部异常记录已删除。<br>误发补贴及关联奖金已追回，考勤与5天年假已恢复。</div><p>这份记录，属于本人。</p>`;if(id==='normal')body=`<div class="endquote">感谢您的理解。</div><section class="card"><div class="cardhead"><h2>新的薪资通知</h2>${badge('自动发放')}</div><div class="bigstat">+100<span>元</span></div><p>育儿关怀</p></section>`;if(id==='cat')body=`<div class="warningbox">原员工张佳诚：已离职。<br>正在重新识别员工身份……识别完成。</div><div class="inline">${avatar('🐈','cat end-avatar')}<div><h2>张佳诚</h2><span class="meta">员工身份核验通过</span></div></div><div class="facts sectiongap">${[['员工姓名','张佳诚'],['岗位','运营专员'],['状态','正常出勤'],['绝育状态','已完成'],['恢复情况','良好']].map(([k,v])=>`<div class="keyval"><span class="muted">${k}</span><span>${v}</span></div>`).join('')}</div><div class="cat-ending-photo"><img src="assets/attachments/${encodeURIComponent('胖橘键盘.jpg')}" alt="橘猫趴在公司键盘上"></div><div class="endquote">林雅雯：欢迎回来。</div>`;return `<section class="endpage"><div class="endcode">${code} / 处理完成</div><h1>《${title}》</h1>${body}<div class="endactions inline">${btn('返回标题页','title','','primary')}${btn('结局回溯','replay','','small')}${btn('返回本人确认','returnSelf','','small')}</div></section>`;}
function render(){state.view={...view};persist();if(!state.started){root.innerHTML=titleScreen().replace('调查进度将保存在当前浏览器','系统状态保存在当前浏览器');return;}if(state.app!=='ending'&&!appOpen(state.app))state.app='desktop';const pages={desktop,business,oa,hr,finance,drive,chat,self:selfPage,ending:endingPage};root.innerHTML=shell((pages[state.app]||desktop)());}
function showAttachment(id){if(!act('attachment',{id}))return;const a=DATA.attachments[id];const catPhotos={catSurgery:['胖橘术后侧躺','胖橘眯眼'],catReview:['胖橘睁眼','胖橘纸箱'],catWell:['胖橘翻肚','胖橘工位']};openModal(a.file,`<div class="preview evidence-photo ${a.cat?'catphoto':''}">${a.file.endsWith('.jpg')?`<img src="assets/attachments/${encodeURIComponent(a.file)}" alt="${esc(a.file.replace('.jpg',''))}">`:`<div class="document-preview"><span>DOCX</span><b>${esc(a.label)}</b></div>`}</div>${a.cat?`<div class="cat-strip">${(catPhotos[id]||[]).map(n=>`<img src="assets/attachments/${encodeURIComponent(n+'.jpg')}" alt="橘猫生活照">`).join('')}</div>`:''}`,`<a href="assets/attachments/${encodeURIComponent(a.file)}" download>下载附件</a>`);}
function showHint(){}
function catWarning(){if(!state.otherHandled){toast('请先处理其他异常，再单独核验宠物档案。');return;}const warnings=['警告1 / 3：宠物医疗资料完整，删除后可能影响身份一致性。','警告2 / 3：宠物资料可信度高于当前员工资料。请确认删除对象。','警告3 / 3：系统将重新识别“张佳诚”。此操作将强制执行。'];openModal('强制删除宠物档案',`<p>${warnings[state.catWarnings]}</p><p class="meta">你仍可以保留档案，返回核验页面。</p>`,btn('保留档案','cancelCat','','small')+btn('无视警告，继续删除','catProceed','','danger'));}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action,id=b.dataset.id;switch(a){
case 'submit':return;
case 'start':state.started=true;if(state.app==='ending'&&!state.ending)state.app='desktop';persist();render();break;
case 'nav':navigate(id);break;
case 'title':modal.close();state.started=false;persist();render();break;
case 'close':modal.close();break;
case 'current':view.oa='current';navigate('oa');break;
case 'discoverLeave':if(act('discoverLeave',{})){view.oa='current';navigate('oa');}break;
case 'presencePage':view.oa='presence';navigate('oa');break;
case 'oaTab':view.oa=id;navigate('oa');break;
case 'hrTab':view.hr=id;navigate('hr');break;
case 'financeTab':view.finance=id;navigate('finance');break;
case 'anomaly':if(!allowed(DATA.anomalies.find(x=>x.day===+b.dataset.day)?.gate))return;view.oa='detail';view.day=+b.dataset.day;navigate('oa');break;
case 'attachment':showAttachment(id);break;
case 'zoomWedding':showAttachment('wedding',b.dataset.zoom==='1');break;
case 'presenceEvidence':{const p=DATA.presence.find(x=>x[0]===id);openModal(p[2],`<p>本月28日 ${p[1]}</p><div class="infobox">${p[3]}</div>`,btn('作为在岗证据提交','presenceSubmit',`data-id="${id}"`,'primary'));break;}
case 'presenceSubmit':if(act('presence',{id},'在岗证据已提交。')){modal.close();render();}break;
case 'review':{const day=+b.dataset.day;const item=DATA.anomalies.find(x=>x.day===day);if(!state.attachments.includes(item.attachment)){toast('请先查看本日附件，再核验材料。');break;}if(act('review',{day},day===6?'已记录：暂存疑，实际申请人无法确认。':'本日材料已核验。'))render();break;}
case 'catUnknown':openModal('实际申请人核验','<p>缺少可确认来源，暂存疑。</p><p class="meta">保留为未归属记录，继续核验其他信息。</p>');break;
case 'trip':{if(!act('trip',{city:b.dataset.city}))break;const t=DATA.trips.find(t=>t.city===b.dataset.city);openModal(t.city+' · 原始票据',`<div class="facts"><div class="keyval">项目编号<strong>${t.project}</strong></div><div class="keyval">部门<strong>${t.dept}</strong></div></div><p class="sectiongap">${t.receipt}</p><p>同行人：${t.mate}</p><p class="meta">请与企业通讯中的项目安排交叉核验。</p>`);break;}
case 'logs':view.oa='logs';navigate('oa');break;
case 'migrationLog':if(act('migrationLog',{}))render();break;
case 'salary':if(act('salary',{}))render();break;
case 'folder':view.folder=id;render();break;
case 'archive':if(!state.solved.migration)return;openModal('解压完成','<p>关于张佳诚异常情况内部说明-严禁外传.zip</p><p class="meta">共1个文件</p>'+attachmentButton('catWell'),'<a href="assets/attachments/关于张佳诚异常情况内部说明-严禁外传.zip" download>下载压缩包</a>');break;
case 'searchTerm':view.query=b.dataset.term;view.chat=null;navigate('chat');break;
case 'chatopen':if(act('chat',{id})){if(!['weddingChat','migrationChat'].includes(id))view.query='';view.chat=id;navigate('chat');if(id==='migrationChat'&&state.solved.migration)toast('模板来源已关联，年假明细已恢复。');}break;
case 'chatBack':view.chat=null;render();break;
case 'clearSearch':view.query='';view.chat=null;render();break;
case 'earliest':if(act('earliest',{})){view.query='';view.chat='originChat';render();}break;
case 'leave':view.hr='leave';navigate('hr');break;
case 'profile':openModal('个人信息',`<div class="profile-page">${avatar(state.ending==='cat'?'🐈':'张佳诚',state.ending==='cat'?'cat profile-photo':'profile-photo')}<div><h2>张佳诚</h2><p class="muted">运营专员 · 运营部</p></div></div><div class="profile-grid"><div><span>员工编号</span><strong>QH-OP-026</strong></div><div><span>办公地点</span><strong>广州</strong></div><div><span>直属主管</span><strong>罗子豪</strong></div><div><span>当前状态</span><strong>${state.ending==='cat'?'正常出勤':state.leaveDiscovered?'休病假':state.workBlocked?'状态同步异常':'正常出勤'}</strong></div></div><p class="meta sectiongap">人员主数据由HR档案与OA考勤同步。</p>`);break;
case 'businessOpen':{const tasks={campaign:['华南渠道9月活动排期','广州天河店：9月12日；深圳南山店：9月15日。两地物料均已登记，等待运营确认。'],report:['OP-026 周运营数据复核','新增线索 428，转化率 18.6%，退款异常 3 笔。请确认数据后提交周报。'],vendor:['秋季专题页素材验收','桌面端首屏、移动端切图和12张商品卡均已到件。尺寸检查通过。']};const t=tasks[id];openModal(t[0],`<div class="work-doc"><div class="doc-head">启衡运营中心 · 内部任务单</div><p>${t[1]}</p><div class="keyval"><span class="muted">负责人</span><span>张佳诚</span></div><div class="keyval"><span class="muted">协作人</span><span>周敏、贺磊</span></div></div>`,btn('暂存','close','','small')+btn(state.businessDone?.includes(id)?'已完成':'确认并完成','businessDone',`data-id="${id}"`,'primary'));break;}
case 'businessDone':if(id==='report'&&!state.solved.todayPresence){if(!act('businessCheck',{id}))break;modal.close();render();openModal('提交失败','<div class="warningbox">员工状态异常，当前任务暂无法提交。</div><p class="meta">错误代码：EMP-STATUS-409。具体状态未返回。</p>',btn('返回工作台','close','','primary'));break;}state.businessDone=state.businessDone||[];if(!state.businessDone.includes(id))state.businessDone.push(id);persist();modal.close();render();toast('任务状态已更新。');break;
case 'compDocument':if(!act('compDocument',{id}))break;if(id==='manual')openModal('人工调整审批单 · QH-PAY-0928','<div class="tablewrap"><table><thead><tr><th>调整项目</th><th>金额</th><th>提出 / 经办</th></tr></thead><tbody><tr><td>项目临时支持奖</td><td>1800元</td><td>周敏 / 贺磊</td></tr><tr><td>销售协作奖</td><td>1600元</td><td>何骏 / 贺磊</td></tr><tr><td>跨部门支持奖</td><td>1200元</td><td>周敏 / 贺磊</td></tr><tr><td>行政协同奖</td><td>1400元</td><td>周敏 / 贺磊</td></tr></tbody></table></div><p class="meta sectiongap">状态：本月工资预结算，尚未发放。</p>');else openModal('系统福利触发规则','<div class="facts"><div class="keyval"><span>婚庆礼金</span><strong>800元</strong></div><div class="keyval"><span>育儿关怀</span><strong>300元</strong></div><div class="keyval"><span>宠物慰问</span><strong>50元</strong></div></div><p class="meta sectiongap">系统依据员工主档案字段自动生成，无人工审批记录。</p>');break;
case 'templateOrigin':if(!act('earliest',{}))break;if(!act('chat',{id:'originChat'}))break;view.query='';view.chat='originChat';navigate('chat');break;
case 'opinionOpen':openModal('其他问题 / 其他意见',`<form data-form="opinion"><label>你还有什么想问的？<input name="text" placeholder="例如：我的意见呢？" required></label><div class="sectiongap">${btn('提交','submit','','primary')}</div></form>`);break;
case 'goodConfirm':openModal('删除全部异常记录','<p>删除全部异常记录 + 追回全部误发补贴 + 恢复考勤。</p><div class="warningbox">系统误发1150元、关联补偿奖金6000元冲回；恢复扣款665.52元及5天年假。<br>个人资料将恢复为：张佳诚 / 运营专员 / 正常出勤。</div>',btn('返回核对','close','','small')+btn('确认清理并恢复考勤','ending','data-id="good"','primary'));break;
case 'ending':if(act('ending',{id})){modal.close();render();window.scrollTo(0,0);}break;
case 'handleOthers':if(state.otherHandled){catWarning();break;}openModal('逐项处理异常','<p>先纠正婚姻、子女、年假、差旅、住址及薪资异常。宠物档案保留为待单独核验。</p>',btn('返回','close','','small')+btn('处理其他异常，保留宠物待核验','handleOthersConfirm','','primary'));break;
case 'handleOthersConfirm':if(act('handleOthers',{})){modal.close();render();}break;
case 'catDelete':catWarning();break;
case 'cancelCat':state.catWarnings=0;persist();modal.close();break;
case 'catProceed':if(act('catWarning',{})){if(state.ending==='cat'){modal.close();render();window.scrollTo(0,0);}else catWarning();}break;
case 'catChoice':state.catChoice=id;persist();render();break;
case 'returnSelf':state.ending=null;state.catWarnings=0;state.app='self';state.started=true;persist();render();break;
case 'replay':if(!state.endings.length){toast('尚未获得结局。');break;}openModal('结局回溯',`<p>已获得：${state.endings.map(k=>({true:'我的意见呢',good:'本人',normal:'那就这样吧',cat:'喵'}[k])).join('、')}</p><p class="meta">返回最终选择可体验三个主线结局。特殊处理仍需在档案中完成。</p>`,btn('返回最终选择','replayConfirm','','primary'));break;
case 'replayConfirm':if(!resumeFinal()){toast('尚无可回溯的最终选择。');break;}modal.close();render();break;
case 'restart':case 'clear':openModal(a==='clear'?'清除全部进度':'重新开始',`<p>${a==='clear'?'将清除本机全部核验进度、结局记录和标题页彩蛋。':'将清除当前调查、谜题、已解锁内容和结局记录，进度从0开始。'}</p>`,btn('取消','close','','small')+btn('确认','resetConfirm','data-all="1"','danger'));break;
case 'resetConfirm':resetGame(b.dataset.all==='1');view={oa:'current',day:27,finance:'travel',hr:'profile',chat:null,query:'',folder:'全部'};modal.close();render();break;
}});
document.addEventListener('submit',e=>{const form=e.target.closest('[data-form]');if(!form)return;e.preventDefault();const type=form.dataset.form;const formData=new FormData(form);const values=Object.fromEntries(formData);if(type==='presenceBatch'){const ids=formData.getAll('records');if(ids.length!==DATA.presence.length){toast('请勾选全部四项记录后统一提交。');return;}for(const id of ids)transition('presence',{id});render();toast('四项在岗记录已统一提交。');return;}if(type==='chatSearch'){view.query=values.q.trim();view.chat=null;render();return;}if(type==='trueEnding'){state.selfOpinionText=values.opinion||'以后涉及我的事情，请先问我。';if(act('ending',{id:'true',confirmRequired:values.confirmRequired==='on'})){modal.close();render();window.scrollTo(0,0);}return;}if(!act(type,values))return;if(type==='opinion')modal.close();if(type==='origin')navigate('self');else render();const messages={marriage:'实际申请人核验通过；14日关联差旅单已恢复显示。',travel:'四城归类完成；18日关联导入批次已显示在共享盘。',migrationSource:'操作来源已确认。',leaveBalance:'余额核验完成。',compensation:'补发审批记录已确认；OA操作日志新增关联模板记录。',opinion:'本人意见字段已添加。'};if(messages[type])toast(messages[type]);});
modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close();}});
window.addEventListener('storage',e=>{if(e.key===SAVE_KEY){state=loadState();render();toast('已同步另一标签页保存的进度。');}});
render();
